package checkers.inference;

import java.util.LinkedList;
import java.util.List;

import checkers.inference.model.Constraint;

/**
 * Constraint manager holds constraints that are generated by InferenceVisitor.
 *
 * @author mcarthur
 *
 */
public class ConstraintManager {

    private List<Constraint> constraints = new LinkedList<Constraint>();

    public List<Constraint> getConstraints() {
        return constraints;
    }

    public void add(Constraint constraint) {
        constraints.add(constraint);
    }
}
