#!/bin/sh

# Fail the whole script if any command fails
set -e

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

CFI=$(cd ${myDir}/../ && pwd)

if [ ! -d $CFI/lib ] ; then
    mkdir $CFI/lib
fi

LIB=$(cd ${CFI}/lib/ && pwd)

## Fetching Lingeling solver
LINGELING_ARCHIVE=http://fmv.jku.at/lingeling/lingeling-bcj-78ebb86-180517.tar.gz

if [ -e $LIB/lingeling/lingeling ] ; then
    echo "Found existing lingeling in $LIB/lingeling, exiting from the shell script."
    exit 0
elif [ -e $LIB/lingeling.tar.gz ] ; then
    echo "Found existing lingeling.tar.gz in $LIB, skip downloading lingeling."
else
    echo "Downloading lingeling from $LINGELING_ARCHIVE..."
    echo "Running cmd: (cd $LIB && wget -O lingeling.tar.gz $LINGELING_ARCHIVE)"
    (cd $LIB && wget -O lingeling.tar.gz $LINGELING_ARCHIVE)
    echo "cmd: (cd $LIB && wget -O lingeling.tar.gz $LINGELING_ARCHIVE) Done."
    echo "Downloaded lingeling.tar.gz in directory $LIB."
fi

echo "Unziping lingeling.tar.gz..."
echo "Running cmd: (cd $LIB && tar -xf lingeling.tar.gz && mv lingeling-* lingeling)"
(cd $LIB && tar -xf lingeling.tar.gz && mv lingeling-* lingeling)
echo "cmd: (cd $LIB && tar -xf lingeling.tar.gz && mv lingeling-* lingeling) Done."
echo "Unziped lingeling.tar.gz into directory $LIB/lingeling."

echo "Compiling lingeling..."
echo "Running cmd: (cd $LIB/lingeling && ./configure.sh && make --silent && ./lingeling --version)"
(cd $LIB/lingeling && ./configure.sh && make --silent && ./lingeling --version)
echo "cmd: (cd $LIB/lingeling && ./configure.sh && make --silent && ./lingeling --version) Done."
echo "Compiled lingeling successfully."

echo "Building lingeling done."
