#!/bin/sh

# Fail the whole script if any command fails
set -e

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

# Note: travis image uses ubuntu 14.04 and will not work with the 16.04 binaries
# 14.04 version seems to work locally on all ubuntu versions above 14.04
UBUNTU_Z3="https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1-x64-ubuntu-14.04.zip"

MAC_Z3="https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1-x64-osx-10.11.6.zip"


case `uname -s` in
    'Darwin')
        Z3_ZIP=$MAC_Z3
        DY_LIB_SUFFIX=dylib
    ;;
    *)
        # Assume it is ubuntu OS.
        Z3_ZIP=$UBUNTU_Z3
        DY_LIB_SUFFIX=so
    ;;
esac

ROOT=$(cd ${myDir}/../../ && pwd)

# z3 jar file and dylib files should either exist together or not exist at all,
# so just check if the jar file exists.
if [ -e $ROOT/z3/bin/com.microsoft.z3.jar ] ; then
    echo "Found existing z3 in $ROOT/z3/bin/, skip downloading z3."
else
    echo "Downloading Z3 from $Z3_ZIP..."
    echo "Running cmd: (cd $ROOT && wget $Z3_ZIP -O z3.zip && unzip z3.zip && mv $ROOT/z3-* $ROOT/z3)"
    (cd $ROOT && wget -q $Z3_ZIP -O z3.zip && unzip z3.zip && mv $ROOT/z3-* $ROOT/z3)
    echo "cmd: (cd $ROOT && wget $Z3_ZIP -O z3.zip && unzip z3.zip && mv $ROOT/z3-* $ROOT/z3) Done."
    echo "Downloaded z3 into directory $ROOT/z3"
fi

if [ ! -d $ROOT/checker-framework-inference/lib ] ; then
    mkdir $ROOT/checker-framework-inference/lib
fi

# Copy build result into CFI lib dir
echo "Copying $ROOT/z3/bin/com.microsoft.z3.jar into $ROOT/checker-framework-inference/lib"
(cp $ROOT/z3/bin/com.microsoft.z3.jar $ROOT/checker-framework-inference/lib)
echo "Copy done."

echo "Copying $ROOT/z3/bin/libz3.$DY_LIB_SUFFIX into $ROOT/checker-framework-inference/lib"
(cp $ROOT/z3/bin/libz3.$DY_LIB_SUFFIX $ROOT/checker-framework-inference/lib)
echo "Copy done."

echo "Copying $ROOT/z3/bin/libz3java.$DY_LIB_SUFFIX into $ROOT/checker-framework-inference/lib"
(cp $ROOT/z3/bin/libz3java.$DY_LIB_SUFFIX $ROOT/checker-framework-inference/lib)
echo "Copy done."
