#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.inference.InferenceDevelLauncher
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

ROOT=$(cd ${myDir}/../../ && pwd)

langtoolsDir="$ROOT"/jsr308-langtools
annoToolsDir="$ROOT"/annotation-tools
stubparserDir="$ROOT"/stubparser
cfDir="$ROOT"/checker-framework
cfiDir="$ROOT"/checker-framework-inference
afuDir="${annoToolsDir}"/annotation-file-utilities

distDir="$cfiDir"/dist

jdkPaths="${cfDir}"/checker/dist/jdk8.jar

CFBuild="${langtoolsDir}"/build/classes:"${annoToolsDir}"/scene-lib/bin:"${cfDir}"/dataflow/build:"${cfDir}"/javacutil/build:"${stubparserDir}"/javaparser-core/target/stubparser.jar:"${afuDir}"/lib/options-all-0.3.1.jar:"${afuDir}"/lib/plume-util-0.0.1.jar:"${afuDir}"/lib/guava-20.0.jar:"${cfDir}"/framework/build:"${cfDir}"/checker/build

CFIBuild="${cfiDir}/build/classes/java/main"

dependenciesJar="${distDir}/dependencies.jar"

if [ ! -f "${dependenciesJar}" ];
then
   echo "Dependencies Jar not found. Run './gradlew dependenciesJar' to build it."
   exit 1
fi

classpath=${CFBuild}:${CFIBuild}:${dependenciesJar}

# append system CLASSPATH to -classpath, so that external checker could export their
# class files in system CLASSPATH, and let InferenceDevelLauncher append them in -classpath
# when invoking InferenceMain.
# TODO: using system CLASSPATH also seems not nice, we should refactor the InferenceLauncher
# and InferenceDevelLuancher, to have a better design on how to passing javac and CF arguments.
if [ "$CLASSPATH" != "" ] ; then
    classpath=${classpath}:${CLASSPATH}
fi

eval "java" \
     "-DInferenceDevelLauncher.binary=${distDir} " \
     "-DInferenceDevelLauncher.runtime.cp=${classpath} " \
     "-DInferenceDevelLauncher.annotated.jdk=${jdkPaths} " \
     "-classpath ${classpath} " \
     "checkers.inference.InferenceDevelLauncher " "$@"
