#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.inference.InferenceLauncher
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

ROOT=$(cd ${myDir}/../../ && pwd)

langtoolsDir="$ROOT"/jsr308-langtools

distDir=$myDir"/../dist"

runtimeBCP=""
java -version 2>&1 | grep version | grep 1.8 > /dev/null
if [ $? -eq 0 ]; then
    runtimeBCP="${langtoolsDir}/cfmake/javac-jdk.jar"
fi

eval "java -DInferenceLauncher.runtime.bcp="$runtimeBCP" -classpath "$distDir"/checker.jar:"$distDir"/checker-framework-inference.jar  checkers.inference.InferenceLauncher " "$@"
