#!/bin/sh

#
# This file simply redirects all passed arguments
# to checkers.inference.InferenceDevelLauncher
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

ROOT=$(cd ${myDir}/../../ && pwd)

annoToolsDir="$ROOT"/annotation-tools
cfDir="$ROOT"/checker-framework
cfiDir="$ROOT"/checker-framework-inference

distDir="$cfiDir"/dist

jdkPaths="${cfDir}"/jdk/annotated

CFBuildDirs="${annoToolsDir}"/scene-lib/bin:"${cfDir}"/dataflow/build:"${cfDir}"/javacutil/build:"${cfDir}"/stubparser/build:"${cfDir}"/framework/build:"${cfDir}"/checker/build
CFIBuildDirs="${cfiDir}/bin"

SAT4jJars="${distDir}"/org.ow2.sat4j.core-2.3.4.jar:"${distDir}"/org.ow2.sat4j.maxsat-2.3.4.jar:"${distDir}"/org.ow2.sat4j.pb-2.3.4.jar
OtherJars="${distDir}"/plume.jar:"${distDir}"/annotation-file-utilities.jar:"${SAT4jJars}":"${distDir}"/gson-1.7.2.jar:"${distDir}"/json-simple-1.1.1.jar:"${distDir}"/mockito-all-1.8.4.jar

eval "java" \
     "-DInferenceDevelLauncher.binary=${distDir} " \
     "-DInferenceDevelLauncher.runtime.bcp=${CFBuildDirs}:${CFIBuildDirs}:${OtherJars} " \
     "-DInferenceDevelLauncher.annotated.jdk=${jdkPaths} " \
     "-classpath ${CFBuildDirs}:${CFIBuildDirs} " \
     "checkers.inference.InferenceDevelLauncher " "$@"
