#!/bin/sh

#
# This file simply redirects all passed arguments
# to org.checkerframework.framework.util.CheckerMain
#

myDir="`dirname $0`"
case `uname -s` in
    CYGWIN*)
      myDir=`cygpath -m $mydir`
      ;;
esac

if [ "$myDir" = "" ];
then
    myDir="."
fi

distDir=$myDir"/../dist"
eval "java -classpath "$distDir"/checker.jar:"$distDir"/checker-framework-inference.jar checkers.inference.SolutionJaifUpdater " "$@"
