package checkers.inference.model;

import org.checkerframework.javacutil.AnnotationUtils;
import org.checkerframework.javacutil.ErrorReporter;

import checkers.inference.qual.VarAnnot;

import javax.lang.model.element.AnnotationMirror;

/**
 * Represents variables, literals, etc... that have an inherent meaning in the type-system for which we
 * are inferring values.
 *
 * E.g. int literals, or primitive types are always NonNull in the Nullness type system.  Their values
 * will be represented by a ConstantSlot( @NonNull )
 *
 */
public class ConstantSlot extends VariableSlot {

    /**
     * The annotation in the real type system that this slot is equivalent to
     */
    private AnnotationMirror value;

    /**
     *
     * @param value   The actual AnnotationMirror that this ConstantSlot represents.  This AnnotationMirror should
     *                be valid within the type system for which we are inferring values.
     *
     * @param location Used to locate this constant in code, the location should point to the tree that has the inherent
     *                constant value
     *                class MyClass {  String s = "a";  }
     *
     *                The ASTPath for the ConstantSlot( NonNull ) generated by "a" would be the path from the root of
     *                the compilation unit to the tree "a"
     *
     *                Note: For now, ConstantSlot ASTPaths are used solely for debugging purposes, as ConstantSlot
     *                annotations never need to be inserted into Jaif Files
     *
     * @param id      Exactly like a variable id, this will uniquely identify this constant in the entirey of the
     *                program
     */
    public ConstantSlot(AnnotationMirror value, AnnotationLocation location, int id) {
        super(location, id);
        checkAndSetValue(value);
    }

    /**
     *
     * @param value   The actual AnnotationMirror that this ConstantSlot represents.  This AnnotationMirror should
     *                be valid within the type system for which we are inferring values.
     * @param id      Exactly like a variable id, this will uniquely identify this constant in the entirey of the
     *                program
     *
     * The location for slots constructed using this constructor will be AnnotationLocation.MISSING_LOCATION
     */
    public ConstantSlot(AnnotationMirror value, int id) {
        super(id);
        checkAndSetValue(value);
    }

    private void checkAndSetValue(AnnotationMirror value) {
        if (AnnotationUtils.areSameByClass(value, VarAnnot.class)) {
            ErrorReporter.errorAbort("Invalid attempt to create a ConstantSlot with VarAnnot as value: " + value);
        }
        this.value = value;
    }

    @Override
    public boolean isInsertable() {
        return false;
    }

    @Override
    public Kind getKind() {
        return Kind.CONSTANT;
    }

    @Override
    public <S, T> S serialize(Serializer<S, T> serializer) {
        return serializer.serialize(this);
    }

    /**
     * @return The "real" annotation that this ConstantSlot is equal to
     */
    public AnnotationMirror getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((value == null) ? 0 : value.toString().hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ConstantSlot other = (ConstantSlot) obj;
        if (value == null) {
            if (other.value != null)
                return false;
        } else if (!AnnotationUtils.areSame(value,other.value))
            return false;
        return true;
    }
}
